[package]
name = "brainz_macros"
version = "0.1.0"
authors = ["Alexis SULTAN <alex@brindille.org>"]

[dependencies]
syn = "0.11.1"
quote = "0.3.15"
Inflector = "0.11"
percent-encoding = "1.0"
regex = "0.2"

[lib]
proc-macro = true
