[package]
name = "entity_macro"
version = "0.1.0"
authors = ["Alexis SULTAN <alex@brindille.org>"]
edition = "2018"

[dependencies]
quote = "0.6"
Inflector = "0.11"
syn = { version = "0.15", features = ["full", "fold"] }
proc-macro2 = "0.4.0"

[lib]
proc-macro = true
